# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extracting factors for conditional log-linear model
#' 
#' This is an auxiliary function to print out the factors for conditional log-linear model
#' given edge information.
#' 
#' 
#' @param pars a set of parameters
#' @param newcombined a \code{[(2+nc) x m ]} matrix comprised of outcomes (first row), treatments (second row), and confounders (from the third row), where \code{nc} is the number of confounders.
#' 
#' @return a sum of factors.
#' 
#' @export
multimainfunction <- function(pars, newcombined) {
    .Call('_netchain_multimainfunction', PACKAGE = 'netchain', pars, newcombined)
}

#' Calculating normalizing constant in conditional log-linear model.
#'
#' @param pars a set of parameters
#' @param combined a \code{[(2+nc) x m ]} matrix comprised of outcomes (first row), treatments (second row), and confounders (from the third row), where \code{nc} is the number of confounders.
#' @param permutetab a matrix comprised of every possible values for outcome in each row. 
#'
#' @return a normalizing constant
#' @export
#'
multipartition <- function(pars, combined, permutetab) {
    .Call('_netchain_multipartition', PACKAGE = 'netchain', pars, combined, permutetab)
}

#' Derive log-likelihood of conditional log-linear model given parameters.
#'
#' @param pars a set of parameters
#' @param listobservations a collection of \code{[(2+nc) x m ]} matrices comprised of outcomes (first row), treatments (second row), and confounders (from the third row), where \code{nc} is the number of confounders. 
#' @param permutetab a matrix comprised of every possible values for outcome in each row. 
#'
#' @return log-likelihood of conditional log-linear model given parameters, observations, and edge information.
#' @export
#'
multiloglikechain <- function(pars, listobservations, permutetab) {
    .Call('_netchain_multiloglikechain', PACKAGE = 'netchain', pars, listobservations, permutetab)
}

